INSERT INTO pass_statistics (institution_name, toeic_score, is_deleted, gtelp_applicable, notes) VALUES
('5급(행시)', 700, false, false, NULL),
('5급(과학기술)', 700, false, false, NULL),
('7급', 700, false, false, NULL),
('외교관 후보자', 870, false, false, NULL),
('지역인사 7급', 700, false, false, NULL),
('민간경력자 5급', 870, false, false, NULL),
('민간경력자 7급', 790, false, false, NULL),
('인사혁신청 5급 공청', 700, false, false, NULL),
('인사혁신청 7급 공청(세무주사직 제외)', 700, false, false, NULL),
('인사혁신청 7급 공청(세무주사직)', 790, false, false, NULL),
('외교관후보자 신엸및화', 870, false, false, NULL),
('국회사무처 입법고시', 700, false, false, NULL),
('대법원 법원행정고등고시', 700, false, false, NULL),
('소방청 소방간부후보자', 625, false, false, NULL),
('경찰간부후보자', 625, false, false, NULL),
('대통령경호청 특정직 7급', 700, false, false, NULL),
('놌수진흥청 연구직·지도직', 700, false, false, NULL),
('해양경찰청 간부후보자', 625, false, false, NULL),
('게임물관리위원회', 900, false, false, NULL),
('경기관광공사', 800, false, false, NULL),
('경기항만항공사', 600, false, false, NULL),
('국민건강보험공단', 700, false, false, NULL),
('국립부산과학관', 720, false, false, NULL),
('국립국어교육원', 750, false, false, NULL),
('국립국어교육원 WEST 장기', 750, false, false, NULL),
('국립국어교육원 WEST 중기', 800, false, false, NULL),
('국립국어교육원 WEST 단기', 850, false, false, NULL),
('기술보증기금', 760, false, false, NULL),
('기초과학연구원', 700, false, false, NULL),
('대한무역투자진흥공사 (KOTRA)', 850, false, false, NULL),
('대한체육회', NULL, false, false, NULL),
('부산항만공사', 700, false, false, NULL),
('부산항보안공사', 700, false, false, NULL),
('서울관광재단', 800, false, false, NULL),
('서울시립교향악단', NULL, false, false, NULL),
('서울주택도시공사', 800, false, false, NULL),
('에너지경제연구원', 750, false, false, NULL),
('여수광양항만공사', 700, false, false, NULL),
('의항지흥위원회', 750, false, false, NULL),
('우체국물류지원단', NULL, false, false, NULL),
('인체항만공사', 700, false, false, NULL),
('인첸국제공항공사 정규 800', 800, false, false, NULL),
('인첸국제공항공사 인턴 700', 700, false, false, NULL),
('중소벤첫기업진흥공단', 850, false, false, NULL),
('한국가스공사', 700, false, false, NULL),
('한국가스안전공사', 650, false, false, NULL),
('한국공정거래조정원', 800, false, false, NULL),
('한국공항공사 정규 750', 750, false, false, NULL),
('한국공항공사 경력 700', 700, false, false, NULL),
('한국과학기술평가원', 800, false, false, NULL),
('한국과학기술정보연구원', 700, false, false, NULL),
('한국관광공사', 800, false, false, NULL),
('한국국방연구원', 750, false, false, NULL),
('한국국제보건의료재단 인턴 830', 830, false, false, NULL),
('한국국제협력단', 730, false, false, NULL),
('한국기계전기연구원', 750, false, false, NULL),
('한국기초과학지식연구원', 700, false, false, NULL),
('한국남동발전', 700, false, false, NULL),
('한국노인인력개발원', 850, false, false, NULL),
('한국도로공사 700', 700, false, false, NULL),
('한국도로공사 750', 750, false, false, NULL),
('한국디자인진흥원', 700, false, false, NULL),
('한국도시가스공사', 720, false, false, NULL),
('한국소방산업기술원', 750, false, false, NULL),
('한국수력원자력', 750, false, false, NULL),
('한국수자원공사 600', 600, false, false, NULL),
('한국수자원공사 700', 700, false, false, NULL),
('한국수자원조사기술원', 700, false, false, NULL),
('한국통계정보원', 700, false, false, NULL),
('한국시스템안전통합하는켓터', 700, false, false, NULL),
('한국언론진흥재단 정규 900', 900, false, false, NULL),
('한국언론진흥재단 인턴 850', 850, false, false, NULL),
('한국에너지공단한수혁자회', 700, false, false, NULL),
('한국에너지기술연구원', 700, false, false, NULL),
('한국에너지통제기술원', 750, false, false, NULL),
('한국전기연구원', 900, false, false, NULL),
('한국전력공사 정규 700', 700, false, false, NULL),
('한국전력공사 보호 500', 500, false, false, NULL),
('한국정보보호진흥원', 900, false, false, NULL),
('한국천문연구원', 750, false, false, NULL),
('한국포스코공사', 700, false, false, NULL),
('한국항공우주연구원', 815, false, false, NULL),
('한국해양과학기술원', 700, false, false, NULL),
('한국해양진흥공사', 700, false, false, NULL),
('한국헬스코종합연구원', 650, false, false, NULL),
('한국환경공단', 750, false, false, NULL),
('한국환경연구기술원', 700, false, false, NULL),
('한전 KDN', 700, false, false, NULL),
('한전 KPS', 700, false, false, NULL),
('항공안전기술원', 700, false, false, NULL),
('FITI시험연구원', 750, false, false, NULL),
('건강보험심사평가원', NULL, false, false, '독해점수에 200%'),
('한국철도공사', 800, false, false, NULL),
('서울주택도시공사 사무직 800 기술직 700', 700, false, false, NULL),
('한국남부발전', 850, false, false, NULL),
('한국동부발전', 900, false, false, NULL),
('한국수자원공사', 775, false, false, NULL),
('한국도시쳊도항공공사', 750, false, false, NULL),
('한국산업단지공단', 750, false, false, NULL),
('한국산업인력공단', 750, false, false, NULL),
('한국도시이연공사', 700, false, false, NULL),
('한국거래소', 900, false, false, NULL),
('강원대학병원', 700, false, false, NULL),
('국가철도공단', 700, false, false, NULL),
('국민연금공단', 700, false, false, NULL),
('대한주택보증사', 700, false, false, NULL),
('국민체육진흥공단', 750, false, false, NULL),
('신용보증기금', 750, false, false, NULL),
('한국전력거래소', 700, false, false, NULL),
('전남해양항만항공연구원', 700, false, false, NULL),
('중소기업기술정보진흥원', 765, false, false, NULL),
('한국무역보험공사', NULL, false, false, '공인어학성적(TOEIC, TOEFL(IBT), TEPS)으로 대체'),
('도로교통공단', 445, false, false, '이상 한수지에 반영'),
('코레일관광개발', 620, false, false, NULL),
('국방기술지흥연구원', 700, false, false, NULL),
('산업공단인력직업진흥공단', 700, false, false, '이상 개별지에 부여'),
('한국조평공사', 360, false, false, '975점까지 한수지에 소수점 적용'),
('극지연구원(기술직)', 700, false, false, NULL),
('근로복지공단', 700, false, false, NULL);

-- 총 119건
